name: "tagdet_rt"
platform: "tensorrt_plan"
max_batch_size: 1

input [
  {
    name: "images"
    data_type: TYPE_FP32
    dims: [ 3, 640, 480 ]
  }
]

output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ 18900, 7 ]
  }
]

instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]

default_model_filename: "model.plan"
